AWSTemplateFormatVersion: '2010-09-09'
Description: Example Pet Store API written with spark/guice with the aws-serverless-java-container
  library
Outputs:
  SpringBootPetStoreApi:
    Description: URL for application
    Export:
      Name: SparkPetClinicApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/owners
Resources:
  PetStoreFunction:
    Properties:
      CodeUri: s3://lambda-jar-upload/034ea521ad014a4bc9426704dc0a9783
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: solid.humank.serverlesslabs.SparkStreamLambdaHandler::handleRequest
      MemorySize: 512
      Policies: AWSLambdaFullAccess
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
