AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Pet Store API written with SpringBoot with the aws-serverless-java-container library
Resources:
  PetStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: solid.humank.serverlesslabs.SparkStreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/sparkjava-petclinic-1.0.0.jar
      MemorySize: 512
      Policies: AWSLambdaFullAccess
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootPetStoreApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/owners'
    Export:
      Name: SparkPetClinicApi
